# Generated by Django 3.1.3 on 2020-11-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='added',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='periodtracker',
            name='added',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
        migrations.AlterField(
            model_name='periodtracker',
            name='date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='periodtracker',
            name='month',
            field=models.IntegerField(null=True),
        ),
    ]
