# Generated by Django 3.1.3 on 2020-11-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20201116_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='added',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
        migrations.AlterField(
            model_name='periodtracker',
            name='added',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
