# Generated by Django 3.1.1 on 2020-11-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmergencyServices', '0002_auto_20201120_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField()),
                ('pay', models.IntegerField()),
                ('skillsrequired', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='healthemergency',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='healthemergency',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='policeemergency',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='policeemergency',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
