# Generated by Django 3.1.1 on 2020-11-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmergencyServices', '0003_auto_20201121_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='mobile',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='healthemergency',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='healthemergency',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='pay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='skillsrequired',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policeemergency',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='policeemergency',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
