# Generated by Django 3.1.1 on 2020-12-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmergencyServices', '0004_unsafeareas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unsafeareas',
            name='user',
        ),
    ]
